# Generated by Django 4.0.5 on 2022-07-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_person_id_person_p_id_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
