# Generated by Django 4.0.5 on 2022-07-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
