# Generated by Django 4.0.5 on 2022-07-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.RemoveField(
            model_name='state',
            name='country_id',
        ),
    ]
