# Generated by Django 4.0.5 on 2022-07-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_initial_schools_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boys',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
