# Generated by Django 4.0.5 on 2022-07-28 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_state_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.country'),
        ),
    ]
