# Generated by Django 4.0.5 on 2022-07-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_district_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(db_column='state_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.state'),
        ),
    ]
